#!/usr/bin/env python

Import("env")
Import("env_modules")

env_noisecomp = env_modules.Clone()

module_obj = []

env_noisecomp.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
